name: Sync
on:
  push:
    branches:
      - main

jobs:
  synchronize-branch:
    runs-on: ubuntu-latest
    name: Sync branch
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Node
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: Opening pull request
        id: pull
        uses: ./
        with:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          FROM_BRANCH: "main"
          TO_BRANCH: "develop"
          REVIEWERS: "Elph"